; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = 

[env]
monitor_speed = 115200
custom_prog_name = retro
custom_prog_version = V3.8.0
board_build.partitions = partitions.csv
board_build.f_flash = 80000000L
board_build.flash_mode = qio
build_unflags = -fno-rtti
build_flags = 
	-D ARDUINO_RUNNING_CORE=0
	-D BUILD_ENV_NAME=$PIOENV
build_src_flags = -Wunknown-pragmas

[env:esp32dev]
extends = fabgl_base
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.17
monitor_speed = 115200
lib_deps = https://github.com/fdivitto/FabGL.git
board_build.f_cpu = 240000000LL
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
build_unflags = -Os
build_flags = 
	-O3
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-ffunction-sections
	-fdata-sections
	-ffast-math
	-fstrict-aliasing
	-Wl,--gc-sections
	-Wl,--print-memory-usage
	-DCORE_DEBUG_LEVEL=0

[env:release_ttgo_vga32_bluepad]
extends = fabgl_base
platform = espressif32@6.9.0
framework = arduino
platform_packages = framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
board = lolin32
board_build.partitions = huge_app.csv
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
build_type = release
board_build.flash_mode = dio
; sdkconfig.board activa CONFIG_SPIRAM_ALLOW_BSS_SEG, CONFIG_SPIRAM_USE_MALLOC, etc.
; Estas opciones NO funcionan como -D en build_flags, necesitan el sdkconfig real.
board_build.sdkconfig_head = sdkconfig.board
lib_deps = https://github.com/Mamigu2022/FabGL.git
build_unflags = 
	-Os
    -Og
    -O0
build_flags = 
	${env.build_flags}
	-D VIDEO_BACKEND_VGA32
	-D BT_GAMEPAD_INPUT_BLUEPAD
	-D CONFIG_BLUEPAD32_MAX_GAMEPADS=1
	-O3
	;-ffunction-sections
	;-fdata-sections
	-ffast-math
	-fstrict-aliasing
	;-Wl,--gc-sections
	-Wl,--print-memory-usage
	-D CORE_DEBUG_LEVEL=0